import {
  Receipt,
  Gift,
  Users,
  UtensilsCrossed,
  ShieldCheck,
  TrendingUp,
  FileText,
  Bike,
  Search,
  DoorOpen,
  Store,
  Megaphone,
  Shield,
  MessageCircle,
  Map,
  Repeat,
  Coins,
  PenLine,
  BarChart3,
  Package,
  Gem,
  FolderOpen,
  Sparkles,
} from "lucide-react";

export const ROADMAP_ICON_MAP = {
  Receipt,
  Gift,
  Users,
  UtensilsCrossed,
  ShieldCheck,
  TrendingUp,
  FileText,
  Bike,
  Search,
  DoorOpen,
  Store,
  Megaphone,
  Shield,
  MessageCircle,
  Map,
  Repeat,
  Coins,
  PenLine,
  BarChart3,
  Package,
  Gem,
  FolderOpen,
};

export const ROADMAP_ICON_FALLBACK = Sparkles;

export const ROADMAP_COLOR_MAP = {
  "brand-blue": "var(--brand-blue)",
  "brand-teal": "var(--brand-teal)",
  "brand-orange": "var(--brand-orange)",
  "brand-bright-cyan": "var(--brand-bright-cyan)",
  "brand-mint": "var(--brand-mint)",
  "brand-deep-cyan": "var(--brand-deep-cyan)",
};
